# **HW02 - EDA cycle.**

## Задача: найти датасет *(много данных, много категорий, есть пропуски)* и провести EDA.
- Сбор.
- Очистка.
- Исследование.
- Предобработка.
- Гипотезы и выводы.

## 1) Выбор датасета
В качестве датасета я выбрал **Spotify Tracks Dataset** с kaggle *(https://www.kaggle.com/datasets/maharshipandya/-spotify-tracks-dataset)*  
**Сам датасет достаточно хороший, в нем нет пропусков, поэтому я исскуственно создам пропуски.**
### Пару слов о полях датасете (кроме очевидных параметров):
- popularity - популярность песни от 0 до 100, где 100 - очень популярная. 
- explicit - откровенные тексты (я не знаю как это нормально и правильно перевести).
- danceability - от 0 до 1 насколько песня танцевальная.
- energy - здесь понимается скорость, громкость, энергия песни. од 0 до 1 (спокойная, энергичная).
- key - тональность песни. 0 - C, 1 - C#, и т.д.
- loudness - громкость песни в децибеллах.
- mode - минорная (0) или мажорная (1) тональность.
- speechiness - показывает как много текста в песне. от 0 до 1. 1 - подкаст, 0 - мелодия, выше 0.66 - песня где много слов, 0.33 - 0.66, как правило обычная песня, например рэп, ниже 0.33 - песня, где мало слов.
- acousticness - показывает вероятность, с которой песня аккустическая.
- instrumentalness - показывает вероятность, с которой песня почти без вокала.
- liveness - показывает вероятность, с которой песня была записана в лайве.
- valence - показывает вероятность, с которой песня позитивная.
- time_signature - ритм песни (цифра / 4).  
*Остальное по идее понятно*.

## 2) Быстрый обзор данных
### 2.1) Загрузка датасета и его порча.
Еще я переведу миллисекунды в минуты, название также поменяю.

In [1]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd
import numpy as np

df = pd.read_csv("spotify-tracks-dataset.csv", index_col = 0) #вручную изменил название первого столбца (track_number), т.к. оно было пустое
pd.set_option('display.max_columns', None) #почему-то без этого он не выводит поле key

np.random.seed(42)

num_deletion = 10000

df['explicit'] = df['explicit'].astype(int) #меняем bool на float, чтобы можно было занулить некоторые элементы из этого стоблца

for idx in range (num_deletion):
    row_idx = np.random.randint(0, len(df))
    col_idx = np.random.randint(0, len(df.columns))
    df.iloc[row_idx, col_idx] = np.nan #вот из-за того, что мы присваиваем nan, у нас все int превратятся во float
df['duration_ms'] = df['duration_ms'] / 60000
df = df.rename(columns={'duration_ms': 'duration_min'})

### 2.2) df.head(), df.tail(), df.shape.

In [2]:
display(df.head())
display(df.tail())
print("Dataset shape: ", df.shape)

,track_id,artists,album_name,track_name,popularity,duration_min,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
track_number,,,,,,,,,,,,,,,,,,,,
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73.0,3.844433,0.0,0.676,0.4610,1.0,-6.746,0.0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4.0,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55.0,2.493500,0.0,0.420,0.1660,1.0,-17.235,1.0,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4.0,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,NaN,To Begin Again,57.0,3.513767,0.0,0.438,0.3590,0.0,-9.734,1.0,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4.0,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71.0,3.365550,0.0,0.266,0.0596,0.0,-18.515,1.0,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3.0,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82.0,3.314217,0.0,0.618,0.4430,2.0,-9.681,1.0,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4.0,acoustic

,track_id,artists,album_name,track_name,popularity,duration_min,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
track_number,,,,,,,,,,,,,,,,,,,,
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21.0,6.416650,0.0,0.172,0.235,5.0,-16.393,1.0,0.0422,0.640,0.928,0.0863,0.0339,125.995,5.0,world-music
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22.0,6.416667,0.0,0.174,0.117,0.0,-18.318,0.0,0.0401,0.994,0.976,0.1050,0.0350,85.239,4.0,world-music
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22.0,4.524433,0.0,0.629,0.329,0.0,-10.895,0.0,0.0420,0.867,0.000,0.0839,0.7430,132.378,4.0,world-music
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41.0,4.731550,0.0,0.587,0.506,7.0,-10.889,1.0,0.0297,0.381,0.000,0.2700,0.4130,135.960,4.0,world-music
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22.0,4.030433,0.0,0.526,0.487,1.0,-10.204,0.0,0.0725,0.681,0.000,0.0893,0.7080,79.198,4.0,world-music

Dataset shape:  (114000, 20)

### 2.3) df.info(), df.describe(), df.describe(include = "str").

In [3]:
df.info()
display(df.describe())
display(df.describe(include = "str"))

<class 'pandas.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_id          113512 non-null  str
 1   artists           113501 non-null  str
 2   album_name        113519 non-null  str
 3   track_name        113519 non-null  str
 4   popularity        113517 non-null  float64
 5   duration_min      113513 non-null  float64
 6   explicit          113506 non-null  float64
 7   danceability      113483 non-null  float64
 8   energy            113538 non-null  float64
 9   key               113492 non-null  float64
 10  loudness          113558 non-null  float64
 11  mode              113488 non-null  float64
 12  speechiness       113467 non-null  float64
 13  acousticness      113505 non-null  float64
 14  instrumentalness  113446 non-null  float64
 15  liveness          113499 non-null  float64
 16  valence           113466 non-null  float64
 17  tempo             113484 non-null  float64
 18  time_signature    113505 non-null  float64
 19  track_genre       113505 non-null  str
dtypes: float64(15), str(5)
memory usage: 17.4 MB

,popularity,duration_min,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,113517.000000,113513.000000,113506.000000,113483.000000,113538.000000,113492.000000,113558.000000,113488.000000,113467.000000,113505.000000,113446.000000,113499.000000,113466.000000,113484.000000,113505.000000
mean,33.234397,3.800723,0.085476,0.566749,0.641378,5.309379,-8.259645,0.637530,0.084653,0.314950,0.156130,0.213607,0.474083,122.147690,3.904216
std,22.305946,1.790050,0.279589,0.173547,0.251536,3.559888,5.030673,0.480716,0.105780,0.332568,0.309603,0.190417,0.259240,29.978045,0.432347
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17.000000,2.900850,0.000000,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.213000,4.000000
50%,35.000000,3.548483,0.000000,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.018000,4.000000
75%,50.000000,4.358650,0.000000,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049300,0.274000,0.683000,140.071000,4.000000
max,100.000000,87.288250,1.000000,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

,track_id,artists,album_name,track_name,track_genre
count,113512,113501,113519,113519,113505
unique,89426,31360,46465,73375,114
top,6S3JlDAGk3uu3NtZbPnuhS,The Beatles,Alternative Christmas 2022,Run Rudolph Run,electronic
freq,9,277,194,150,1000

### 2.4) Проверки качества: isnull().sum(), поиск дубликатов, проверка адекватности типов данных.

In [4]:
print(df.isnull().sum())
print("Duplicates: ", df.duplicated().sum())
print(df.dtypes)

track_id            488
artists             499
album_name          481
track_name          481
popularity          483
duration_min        487
explicit            494
danceability        517
energy              462
key                 508
loudness            442
mode                512
speechiness         533
acousticness        495
instrumentalness    554
liveness            501
valence             534
tempo               516
time_signature      495
track_genre         495
dtype: int64
Duplicates:  382
track_id                str
artists                 str
album_name              str
track_name              str
popularity          float64
duration_min        float64
explicit            float64
danceability        float64
energy              float64
key                 float64
loudness            float64
mode                float64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature      float64
track_genre             str
dtype: object

### 2.5) Мини-вывод по датасету.
В датасете 114000 записей, 20 разных параметров, около 400 дубликатов. Исскуственно испорчены некоторые записи, поэтому будет хорошо учиться на таком датасете.

## 3) Пропуски и очистка.
### 3.1) Dropna(), fillna(). 
- Если нет параметра типа string, то я просто дропну эту строку, т.к. невозможно задать стандартное, среднее значение жанру или популярное значение жанру, названию или исполнителю. Популярное тоже не возьмешь, т.к. в датасете не собраны песни одного жанра либо автора. Эти параметры достаточно важные, они будут учитываться, но т.к. мы их заполнить не можем, мы их просто дропнем.  
- Все float64, мы заполним просто средними значениями. Причина та же - непонятно, какое значение выбрать, поэтому чтобы не ломать статистику возьмем везде среднее, даже там, где только 0 и 1.  
- В конце концов пустых ячеек не так много, и чем больше мы их сохраним, тем лучше.  
- В итоге мы удалили около 2500 ячеек, и 7500 восстановили. Это также проверяется тем, что у нас 5 полей типа string, количество пропусков мы можем посчитать, взяв данные из таблицы.
- Заполнение модой я не хотел использовать, т.к. оно немного ломает статистику, поэтому лучше оставить как есть и анализировать другие параметры.
- В конце снова выведены данные, чтобы посмотреть на количество пропусков.

In [5]:
float_columns = df.select_dtypes(include = ['float64']).columns
df[float_columns] = df[float_columns].fillna(df[float_columns].mean())

str_columns = df.select_dtypes(include = ['str']).columns
df = df.dropna(subset = str_columns)

df.info()
print(df.isnull().sum())

<class 'pandas.DataFrame'>
Index: 111579 entries, 0 to 113999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_id          111579 non-null  str
 1   artists           111579 non-null  str
 2   album_name        111579 non-null  str
 3   track_name        111579 non-null  str
 4   popularity        111579 non-null  float64
 5   duration_min      111579 non-null  float64
 6   explicit          111579 non-null  float64
 7   danceability      111579 non-null  float64
 8   energy            111579 non-null  float64
 9   key               111579 non-null  float64
 10  loudness          111579 non-null  float64
 11  mode              111579 non-null  float64
 12  speechiness       111579 non-null  float64
 13  acousticness      111579 non-null  float64
 14  instrumentalness  111579 non-null  float64
 15  liveness          111579 non-null  float64
 16  valence           111579 non-null  float64
 17  tempo             111579 non-null  float64
 18  time_signature    111579 non-null  float64
 19  track_genre       111579 non-null  str
dtypes: float64(15), str(5)
memory usage: 17.9 MB
track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_min        0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

### 3.2) Как видим, всё прекрасно починено.

## 4) Расширенная статистика
### 4.1) Для числовых колонок выведем: min, max, mean, median, mode.

In [6]:
print("Min:")
print(df.min(numeric_only = True))
print()
print("Max:")
print(df.max(numeric_only = True))
print()
print("Mean:")
print(df.mean(numeric_only = True))
print()
print("Median:")
print(df.median(numeric_only = True))
print()
print("Mode:")
print(df.mode(numeric_only = True).iloc[0])
print()

Min:
popularity           0.0000
duration_min         0.1431
explicit             0.0000
danceability         0.0000
energy               0.0000
key                  0.0000
loudness           -49.5310
mode                 0.0000
speechiness          0.0000
acousticness         0.0000
instrumentalness     0.0000
liveness             0.0000
valence              0.0000
tempo                0.0000
time_signature       0.0000
dtype: float64

Max:
popularity          100.00000
duration_min         87.28825
explicit              1.00000
danceability          0.98500
energy                1.00000
key                  11.00000
loudness              4.53200
mode                  1.00000
speechiness           0.96500
acousticness          0.99600
instrumentalness      1.00000
liveness              1.00000
valence               0.99500
tempo               243.37200
time_signature        5.00000
dtype: float64

Mean:
popularity           33.228790
duration_min          3.800823
explicit              0.085384
danceability          0.566724
energy                0.641312
key                   5.310684
loudness             -8.261511
mode                  0.637379
speechiness           0.084672
acousticness          0.314987
instrumentalness      0.156318
liveness              0.213706
valence               0.474280
tempo               122.132150
time_signature        3.904246
dtype: float64

Median:
popularity           34.000000
duration_min          3.554000
explicit              0.000000
danceability          0.579000
energy                0.683000
key                   5.000000
loudness             -7.026000
mode                  1.000000
speechiness           0.049100
acousticness          0.171000
instrumentalness      0.000045
liveness              0.133000
valence               0.466000
tempo               122.050000
time_signature        4.000000
dtype: float64

Mode:
popularity            0.000000
duration_min          3.800723
explicit              0.000000
danceability          0.566749
energy                0.641378
key                   7.000000
loudness             -8.259645
mode                  1.000000
speechiness           0.084653
acousticness          0.314950
instrumentalness      0.000000
liveness              0.108000
valence               0.474083
tempo               122.147690
time_signature        4.000000
Name: 0, dtype: float64

### 4.2) Посчитаем percentile/quantile (например, 5, 25, 50, 75, 95 перцентили).

In [8]:
print("5 percentile")
print(df.quantile(0.05, numeric_only = True))
print()
print("25 percentile")
print(df.quantile(0.25, numeric_only = True))
print()
print("50 percentile")
print(df.quantile(0.5, numeric_only = True))
print()
print("75 percentile")
print(df.quantile(0.75, numeric_only = True))
print()
print("95 percentile")
print(df.quantile(0.95, numeric_only = True))
print()

5 percentile
popularity           0.000000
duration_min         1.950727
explicit             0.000000
danceability         0.250000
energy               0.155000
key                  0.000000
loudness           -18.053100
mode                 0.000000
speechiness          0.028300
acousticness         0.000146
instrumentalness     0.000000
liveness             0.060700
valence              0.071200
tempo               77.369600
time_signature       3.000000
Name: 0.05, dtype: float64

25 percentile
popularity          17.000000
duration_min         2.903217
explicit             0.000000
danceability         0.456000
energy               0.473000
key                  2.000000
loudness           -10.001000
mode                 0.000000
speechiness          0.036000
acousticness         0.017100
instrumentalness     0.000000
liveness             0.098200
valence              0.261000
tempo               99.377500
time_signature       4.000000
Name: 0.25, dtype: float64

50 percentile
popularity           34.000000
duration_min          3.554000
explicit              0.000000
danceability          0.579000
energy                0.683000
key                   5.000000
loudness             -7.026000
mode                  1.000000
speechiness           0.049100
acousticness          0.171000
instrumentalness      0.000045
liveness              0.133000
valence               0.466000
tempo               122.050000
time_signature        4.000000
Name: 0.5, dtype: float64

75 percentile
popularity           50.000000
duration_min          4.352000
explicit              0.000000
danceability          0.694000
energy                0.853000
key                   8.000000
loudness             -5.015000
mode                  1.000000
speechiness           0.084653
acousticness          0.596000
instrumentalness      0.055300
liveness              0.273000
valence               0.682000
tempo               140.050500
time_signature        4.000000
Name: 0.75, dtype: float64

95 percentile
popularity           69.000000
duration_min          6.446217
explicit              1.000000
danceability          0.824000
energy                0.968000
key                  11.000000
loudness             -2.981000
mode                  1.000000
speechiness           0.268000
acousticness          0.948000
instrumentalness      0.904000
liveness              0.680000
valence               0.911000
tempo               175.046100
time_signature        4.000000
Name: 0.95, dtype: float64

### 4.3) Дисперсия, ассиметрия, эксцесс

In [9]:
print("Variance:")
print(df.var(numeric_only=True))
print()
print("Skewness:")
print(df.skew(numeric_only=True))
print()
print("Kurtosis:")
print(df.kurt(numeric_only=True))
print()

Variance:
popularity          495.377767
duration_min          3.213811
explicit              0.077758
danceability          0.030011
energy                0.062997
key                  12.623189
loudness             25.212683
mode                  0.230096
speechiness           0.011144
acousticness          0.110153
instrumentalness      0.095492
liveness              0.036143
valence               0.066910
tempo               894.631349
time_signature        0.186375
dtype: float64

Skewness:
popularity           0.047067
duration_min        11.331539
explicit             2.973802
danceability        -0.399988
energy              -0.597691
key                 -0.008351
loudness            -2.011662
mode                -0.572803
speechiness          4.661185
acousticness         0.728568
instrumentalness     1.735946
liveness             2.109012
valence              0.114281
tempo                0.234722
time_signature      -4.104366
dtype: float64

Kurtosis:
popularity           -0.918813
duration_min        359.021561
explicit              6.847952
danceability         -0.174018
energy               -0.516534
key                  -1.269174
loudness              5.941640
mode                 -1.667435
speechiness          28.993218
acousticness         -0.941628
instrumentalness      1.281996
liveness              4.401119
valence              -1.018338
tempo                -0.098310
time_signature       26.123076
dtype: float64

- Дисперсия - это мера отклонения данных от среднего значения. По сути это стандартное отклонение в квадрате. Дисперсия показывает насколько сильно разбросаны данные относительно друг друга. В моем случае данные разбросаны сильно, например, по популярности.
- Ассиметрия - это мера, которая показывает, насколько распределение данных смещено относительно нормально. Положительная (хвост справа) и отрицательная (хвост слева). В моем случае менее популярных песен немного больше, чем популярных.
- Эксцесс - это мера, которая показывает насколько мода острая (положительная) или тупая (отрицательная). По сути показывает насколько распределение соответсвует нормальныму по количеству значений.